# Generated by Django 2.1 on 2019-03-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostalmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.AlterField(
            model_name='rooms',
            name='student_id',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
